### ISSUE TITLE
Not build. How to disable secure key check?

### ISSUE THREAD

**Issue by kixiro** [allure-framework/allure-debian#5]
<pre>
# debuild -S
This package has a Debian revision number but there does not seem to be
an appropriate original tar file or .orig directory in the parent directory;
(expected one of allure-commandline_1.4.23.orig.tar.gz, allure-commandline_1.4.23.orig.tar.bz2,
allure-commandline_1.4.23.orig.tar.lzma,  allure-commandline_1.4.23.orig.tar.xz or allure-debian.orig)
continue anyway? (y/n) y
 dpkg-buildpackage -rfakeroot -d -us -uc -S
dpkg-buildpackage: предупреждение: используется команда получения прав root, но уже есть права root
dpkg-buildpackage: пакет исходного кода allure-commandline
dpkg-buildpackage: версия исходного кода 1.4.23-2
dpkg-buildpackage: дистрибутив исходного кода trusty
dpkg-buildpackage: исходный код изменён Ivan Krutov <vania-pooh@yandex-team.ru>
 dpkg-source --before-build allure-debian
 fakeroot debian/rules clean
CDBS:  parsing allure-commandline.zip ...
test -x debian/rules
dh_clean 
 dpkg-source -b allure-debian
dpkg-source: предупреждение: не задан формат исходников в debian/source/format, см. dpkg-source(1)
dpkg-source: предупреждение: каталог исходников «allure-debian» не в виде <пакет исходников>-<оригинальная версия> «allure-commandline-1.4.23»
dpkg-source: инфо: используется формат исходника «1.0»
dpkg-source: инфо: сборка allure-commandline в allure-commandline_1.4.23-2.tar.gz
dpkg-source: инфо: сборка allure-commandline в allure-commandline_1.4.23-2.dsc
 dpkg-genchanges -S >../allure-commandline_1.4.23-2_source.changes
dpkg-genchanges: в закачку включён весь исходный код
 dpkg-source --after-build allure-debian
dpkg-buildpackage: закачка только пакетов исходного кода: родной пакет Debian
Now running lintian...
warning: the authors of lintian do not recommend running it with root privileges!
E: allure-commandline changes: bad-distribution-in-changes-file trusty
W: allure-commandline source: native-package-with-dash-version
W: allure-commandline source: diff-contains-git-control-dir .git
W: allure-commandline source: no-debian-copyright
W: allure-commandline source: ancient-standards-version 3.9.1 (current is 3.9.6)
Finished running lintian.
Now signing changes and any dsc files...
 signfile allure-commandline_1.4.23-2.dsc Ivan Krutov <vania-pooh@yandex-team.ru>
gpg: пропущено "Ivan Krutov <vania-pooh@yandex-team.ru>": закрытый ключ не найден
gpg: /tmp/debsign.t9HqIZNJ/allure-commandline_1.4.23-2.dsc: clearsign failed: закрытый ключ не найден
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed
</pre>

**Comment by vania-pooh** [comment]
@kixiro just update this file and use your name and email instead: https://github.com/allure-framework/allure-debian/blob/master/debian/changelog You should have a GPG key in your local keystore. Probably there's an option to disable signing in ```debuild``` at all but can't find it.
